apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-doom
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: doom
  template:
    metadata:
      labels:
        app: doom
    spec:
      containers:
      - name: doom
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: VNC_PW
          value: "{{ .Values.env.VNC_PW }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]  # Nécessaire pour KasmWeb/Doom
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 512Mi
