apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iot-doom-chart.fullname" . }}
  labels:
    {{- include "iot-doom-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "iot-doom-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "iot-doom-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 6901
              protocol: TCP
          env:
            - name: VNC_PW
              value: "{{ .Values.env.VNC_PW }}"
