{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "iot-doom-chart.fullname" . }}
  labels:
    {{- include "iot-doom-chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.hosts[0].host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.hosts[0].paths[0].path | quote }}
            pathType: {{ .Values.ingress.hosts[0].paths[0].pathType | quote }}
            backend:
              service:
                name: {{ include "iot-doom-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
